# Generated by Django 5.2.4 on 2025-08-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoran', '0014_clients_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteam',
            name='pic',
            field=models.ImageField(upload_to='ourteam/%Y/%m'),
        ),
    ]
