# Generated by Django 5.2.4 on 2025-08-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoran', '0015_alter_ourteam_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourteam',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='ourteam/%Y/%m'),
        ),
    ]
